AWS_COGNITO_APP_NAME = 'cognito-idp'
AWS_USER_POOL_ID = 'us-east-2_CEuXbG7OK'
AWS_REGION_NAME = "us-east-2"
AWS_ACCESS_KEY_ID = "QUtJQUpJM080VlNKV1o3TVI1WEE="
AWS_SECRET_KEY = "eHA1OXFkTnM2QThEay9HQzNmbUhGbnJVSXFERVE0Z2NPNHo2NTJkQw=="
APP_CLIENT_ID = "NHQyb25ibGdiMDN2ZmFlZmJ1ZzR2MzI4bg=="