# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-02 09:20
from __future__ import unicode_literals

import Smart_Valve.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Valve', '0002_auto_20181002_1448'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Smart_Valve.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 14, 50, 19, 964000)),
        ),
    ]
