# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-06 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Valve', '0004_auto_20181006_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 6, 18, 21, 46, 331000)),
        ),
        migrations.AlterField(
            model_name='valve',
            name='status_last_updated_at',
            field=models.TimeField(default=datetime.datetime(2018, 10, 6, 18, 21, 46, 336000)),
        ),
    ]
